server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gibaodb
    username: gibas
    password: terra
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Values: none, create, create-drop, validate, update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

thread:
  time:
    sleep:
      minutes: 30000

pokemon:
  first:
    season: "bulbasaur, ivysaur, venusaur, charmander, charmeleon, charizard, squirtle, wartortle,blastoise, caterpie, metapod, butterfree, weedle, kakuna, beedrill, pidgey,pidgeotto, pidgeot, rattata, raticate, spearow, fearow, ekans, arbok, pikachu,raichu, sandshrew, sandslash, nidoran♀, nidorina, nidoqueen, nidoran♂, nidorino,nidoking, clefairy, clefable, vulpix, ninetales, jigglypuff, wigglytuff, zubat,golbat, oddish, gloom, vileplume, paras, parasect, venonat, venomoth, diglett,dugtrio, meowth, persian, psyduck, golduck, mankey, primeape, growlithe, arcanine,poliwag, poliwhirl, oliwrath, abra, kadabra, alakazam, machop, machoke, machamp,bellsprout, weepinbell, victreebel, tentacool, tentacruel, geodude, graveler, golem,ponyta, rapidash, slowpoke, slowbro, magnemite, magneton, farfetchd, doduo, dodrio,seel, dewgong, grimer, muk, shellder, cloyster, gastly, haunter, gengar, onix,drowzee, hypno, krabby, kingler, voltorb, electrode, exeggcute, exeggutor, cubone,marowak, hitmonlee, hitmonchan, lickitung, koffing, weezing, rhyhorn, rhydon, chansey,tangela, kangaskhan, horsea, seadra, goldeen, seaking, staryu, starmie, mr-mime,scyther, jynx, electabuzz, magmar, insir, tauros, magikarp, gyarados, lapras,ditto, eevee, vaporeon, jolteon, flareon, porygon, omanyte, omastar, kabuto,kabutops, aerodactyl, snorlax, articuno , zapdos , moltres ,dratini, dragonair, dragonite, mewtwo , mew, mewtwo"